# Jekyll Configuration
title: Tomorrow Better Than Today
description: Simple thoughts, daily improvements
author: Your Name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Permalink format for blog posts
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year-:month-:day-:title/

# Default values
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"